
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database:  acebook_development
  url: <%= ENV["DEVELOPMENT_DATABASE_URL"] %>
 
test:
  <<: *default
  database: acebook_test
  

production:
  <<: *default
  database: acebook_production
  url: <%= ENV["PRODUCTION_DATABASE_URL"] %>